### ISSUE TITLE
Deprecation in log

### ISSUE THREAD

**Issue by ottes** [fwartner/ha-openwakeword-installer#4]
just found your integration and tried it, but failed..... same as the other issue, but i saw some warnings more, that you maybe interested in

```
2024-07-09 17:13:08.014 INFO (MainThread) [homeassistant.setup] Setting up wakeword_installer
2024-07-09 17:13:08.020 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'wakeword_installer' calls async_forward_entry_setup for integration, wakeword_installer with title: WakeWord Installer and entry_id: 01J2C0WEXD5CJ7ZHYY02HCJADG, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/wakeword_installer/__init__.py, line 12: hass.async_create_task(, please create a bug report at https://github.com/fwartner/ha-openwakeword-installer/issues
2024-07-09 17:13:08.025 INFO (MainThread) [homeassistant.components.sensor] Setting up wakeword_installer.sensor
2024-07-09 17:13:08.025 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wakeword_installer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/wakeword_installer/sensor.py", line 18, in async_setup_entry
    repository_url = config_entry.data[CONF_URL]
                     ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'url'
2024-07-09 17:13:08.027 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration wakeword_installer with title: WakeWord Installer and entry_id: 01J2C0WEXD5CJ7ZHYY02HCJADG, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2122, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1175, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
```

**Comment by fwartner** [comment]
Should be fixed now :)
